---
version: '2'
services:
  drupal_db:
    container_name: kub_db
    image: mysql:5.7
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
  drupal_web:
    container_name: kub_web
    image: banderson/drupal
    restart: always
    depends_on:
      - drupal_db
    links:
      - drupal_db:drupal_db
    ports:
      - 8088:80
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_HOSTNAME: drupal_db
      MYSQL_PASSWORD: drupal
      MYSQL_PORT: 3306
      MYSQL_USER: drupal
      DRUPAL_ENV: dev
